Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using D2Blog.Helper;
using D2Blog.Models;
using PagedList;
using PagedList.Mvc;

namespace D2Blog.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RequireHttps]
        // GET: BlogPosts
        public ActionResult Index(int? page, string searchbox)
        {
            ViewBag.Search = searchbox;
            var blogList = IndexSearch(searchbox);
            
            var pageSize = 4;
            var pageNumber = (page ?? 1);
            IQueryable<BlogPost> data = null;
            if (User.IsInRole("Admin"))
                data = db.Posts;
            else
                data = db.Posts.Where(b => b.published);

            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchbox)
        {
            IQueryable<BlogPost> result = null;
            if (searchbox != null)
            {
                result = db.Posts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchbox) ||
                                            p.Body.Contains(searchbox) ||
                                            p.Comments.Any(c => c.Body.Contains(searchbox) ||
                                                            c.Author.Firstname.Contains(searchbox) ||
                                                            c.Author.Lastname.Contains(searchbox) ||
                                                            c.Author.Displayname.Contains(searchbox) ||
                                                            c.Author.Email.Contains(searchbox)));

            }
            else
            {
                result = db.Posts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }
        [RequireHttps]
        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }
       
        // GET: BlogPosts/Create
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [RequireHttps]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Body,mediaURL,published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if(String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if(db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "Title Must Be Unique");
                    return View(blogPost);
                }
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/" + fileName)));
                    blogPost.mediaURL = "/Uploads/" + fileName;
                }
                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }
        [RequireHttps]
        [Authorize(Roles = "Admin")]
        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [RequireHttps]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Created,Updated,Title,Slug,Body,mediaURL,published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            //checks for new title to place in Slug
            var slug = StringUtilities.URLFriendly(blogPost.Title);

            if (ModelState.IsValid)
            {
                if (ImageUploadValidator.IsWebFriendlyImage(image) && image != null)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.mediaURL = "/Uploads/" + fileName;
                }    
                blogPost.Updated = DateTimeOffset.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

                 
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [RequireHttps]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [RequireHttps]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Wilten's Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <link rel="shortcut icon" href="~/Spectre_status.jpg" />

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="~/Tales_template/HTML/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Tales_template/HTML/node_modules/bootstrap/dist/css/bootstrap-theme.min.css">

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="~/Tales_template/HTML/node_modules/font-awesome/css/font-awesome.min.css">

    <!-- Google Webfonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600%7CPT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link rel="stylesheet" href="~/Tales_template/HTML/css/styles-bluegreen.css" id="theme-styles">

    <link href="~/Content/Custom.css" rel="stylesheet" />

</head>
<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="#" id="logo">
                    WELCOME TO MY BLOG
                    <!--Use the following line instead if you want to use an image logo-->
                    <!--<img src="img/tales-logo.png" alt="Tales Blog">-->
                </a>
                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".tales-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
                <nav class="pull-right tales-nav">
                    <li class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">
                            <li>
                                @Html.ActionLink("Home", "Index", "BlogPosts")
                            </li>
                            <li class="dropdown active">
                                <a class="dropdown-toggle"
                                   data-toggle="dropdown"
                                   href="#">
                                    Sign In/Out@*Login User/Register*@
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    @{
                                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                        { @Html.AntiForgeryToken() }
                                    }

                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <li>@Html.ActionLink("Hi " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                    }
                                    else
                                    {
                                        @*<li><a href="javascript:document.getElementById('logoutForm').submit()">Log In</a></li>*@
                                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                                        <li>@Html.ActionLink("Register", "Register", "Account")</li>
                                    }
                                </ul>
                            </li>                          
                        </ul>
                    </li>
                </nav>
            </div>

        </div>
        <div class="widewrapper subheader">
            <div class="container">
                <div class="tales-breadcrumb">
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Create New", "Create")
                    }
                </div>
                <div class="tales-searchbox">
                    <form method="get" accept-charset="utf-8">
                        <button class="searchbutton" id="searchbox" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                        <input class="input-block-level" name="searchbox" id="searchbox" type="text" placeholder="Search">
                    </form>
                </div>
            </div>
        </div>
    </header>

    @RenderBody()
    <footer>
        <div class="widewrapper footer">
            <div class="container">
                <div class="row">                    
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i><span class="dark">Contact Me</span></h3>
                        <span>I'm happy to hear from my readers. Thoughts, feedback, critique - all welcome! Drop me a line:</span>

                        <span class="email">
                            <div>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @Html.ActionLink("Message the Author", "Contact", "Home")
                                }
                                else
                                {
                                    <div>Login to contact the author</div>
                                }
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="widewrapper copyright">
            <div class="container">
                <!--Note: Feel free to remove or change this link as you please. A link to HackerThemes is not required by any means-->
                <a>Thanks For Visiting!</a>
            </div>
        </div>
    </footer>
    <script src="//code.jquery.com/jquery-2.2.3.min.js"></script>
    @*<script>window.jQuery || document.write('<script src="Tales_template/HTML/node_modules/jquery/dist/jquery.min.js"><\/script>')</script>*@
    <script src="~/Tales_template/HTML/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Tales_template/HTML/modules/modernizr/modernizr-custom.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>