Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace D2Blog.Models
{
    public class BlogPost
    {
        public BlogPost()
        {
            this.Comments = new HashSet<Comment>();
        }
        public int id{get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        [AllowHtml]
        public string Body { get; set; }
        public string mediaURL { get; set; }
        public bool published { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using D2Blog.Helper;
using D2Blog.Models;
using PagedList;
using PagedList.Mvc;

namespace D2Blog.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RequireHttps]
        // GET: BlogPosts
        public ActionResult Index(int? page, string searchbox)
        {
            ViewBag.Search = searchbox;
            var blogList = IndexSearch(searchbox);
            
            var pageSize = 4;
            var pageNumber = (page ?? 1);
            IQueryable<BlogPost> data = null;
            if (User.IsInRole("Admin"))
                data = db.Posts;
            else
                data = db.Posts.Where(b => b.published);

            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchbox)
        {
            IQueryable<BlogPost> result = null;
            if (searchbox != null)
            {
                result = db.Posts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchbox) ||
                                            p.Body.Contains(searchbox) ||
                                            p.Comments.Any(c => c.Body.Contains(searchbox) ||
                                                            c.Author.Firstname.Contains(searchbox) ||
                                                            c.Author.Lastname.Contains(searchbox) ||
                                                            c.Author.Displayname.Contains(searchbox) ||
                                                            c.Author.Email.Contains(searchbox)));

            }
            else
            {
                result = db.Posts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }
        [RequireHttps]
        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }
       
        // GET: BlogPosts/Create
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [RequireHttps]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Body,mediaURL,published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if(String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if(db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "Title Must Be Unique");
                    return View(blogPost);
                }
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/" + fileName)));
                    blogPost.mediaURL = "/Uploads/" + fileName;
                }
                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }
        [RequireHttps]
        [Authorize(Roles = "Admin")]
        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [RequireHttps]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Created,Updated,Title,Slug,Body,mediaURL,published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            //checks for new title to place in Slug
            var slug = StringUtilities.URLFriendly(blogPost.Title);

            if (ModelState.IsValid)
            {
                if (ImageUploadValidator.IsWebFriendlyImage(image) && image != null)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.mediaURL = "/Uploads/" + fileName;
                }    
                blogPost.Updated = DateTimeOffset.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

                 
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [RequireHttps]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [RequireHttps]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using D2Blog.Models;
using Microsoft.AspNet.Identity;

namespace D2Blog.Controllers
{
    [RequireHttps]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        [RequireHttps]
        [Authorize]
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Author).Include(c => c.Post);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        [RequireHttps]
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        [RequireHttps]
        [Authorize]
        public ActionResult Create(string slug)
        {
            var user = User.Identity.GetUserId();
            var person = db.Users.Find(user);

            ViewBag.AuthorId = person;
            ViewBag.PostId = new SelectList(db.Posts.Where(t => t.Slug == slug), "id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [RequireHttps]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,created,updated,PostId,AuthorId,Body")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.updated = DateTimeOffset.Now;
                comment.AuthorId = User.Identity.GetUserId();
                db.Comments.Add(comment);
                comment.created = DateTimeOffset.Now;
                db.SaveChanges();
                return RedirectToAction("Index", "BlogPosts");
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "Firstname", comment.AuthorId);
            ViewBag.PostId = new SelectList(db.Posts, "id", "Title", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        [RequireHttps]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = User.Identity.GetUserId();
            Comment comment = db.Comments.Find(id);
            if(comment.AuthorId != user && !User.IsInRole("Moderator"))
            {
                return RedirectToAction("Index", "BlogPosts");
            }
            if (comment == null)
            {
                return HttpNotFound();
            }
            var person = db.Users.Find(user);
            ViewBag.AuthorId = person.Id;
            ViewBag.PostId = new SelectList(db.Posts.Where(c => c.id == comment.id), "id", "Title", comment.PostId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [RequireHttps]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,PostId,AuthorId,Body,created,updated,UpdateReason")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.AuthorId = User.Identity.GetUserId();
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.PostId = new SelectList(db.Posts, "id", "Title", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [RequireHttps]
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [RequireHttps]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/BlogPosts/Create.cshtml
@model D2Blog.Models.BlogPost

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create" , "BlogPosts" , FormMethod.Post , new { enctype = "Multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
          <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mediaURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="image" type="file" class="form-control" id="fileUpload" />
                @Html.ValidationMessageFor(model => model.mediaURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                        @Html.EditorFor(model => model.published)
                        @Html.ValidationMessageFor(model => model.published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            tinymce.init({
                selector: '#Body'
            });
        });
        
    </script>
}

Views/BlogPosts/Delete.cshtml
@model D2Blog.Models.BlogPost

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mediaURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mediaURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.published)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/BlogPosts/Details.cshtml
@model D2Blog.Models.BlogPost


@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.Raw(Model.Body)
        </dd>

        <dt>
            @Html.DisplayName("Cover Picture")
        </dt>

        <dd>
            @if (Model.mediaURL != null)
            {
                <img class="img-responsive" src="@Model.mediaURL" alt="" height="184" width="184">
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            <div id="heading" class="col-md-10">
                <div class="panel-group">
                    <div  class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse">Comments:</a>
                            </h4>
                        </div>
                        <div id="collapse" class="panel-collapse collapse nopad">
                            @foreach (var comments in Model.Comments.OrderByDescending(c => c.created))
                            {
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            @Html.Raw(comments.Body)
                                        </div>
                                        <div class="col-md-12">
                                            Author: @comments.Author.Email
                                            <br />
                                            Posted on: @comments.created
                                        </div>
                                        <div class="col-md-12">
                                            @Html.ActionLink("Edit", "Edit", "Comments", new { id = comments.id }, null)
                                        </div>
                                    </div>
                                </div>
                                <br />
                            }
                        </div>
                    </div>
                </div>
            </div>
        </dd>
    </dl>
</div>
<p>
    @if(User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Add Comment", "Create", "Comments", new { Slug = Model.Slug }, null)
    }    
    @if ((User.Identity.IsAuthenticated) && (User.IsInRole("Admin") || (User.IsInRole("Moderator"))))
    {
        @Html.ActionLink("Edit", "Edit", new { Slug = Model.Slug }) 
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Views/BlogPosts/Edit.cshtml
@model D2Blog.Models.BlogPost

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "BlogPosts", FormMethod.Post, new { enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        @Html.HiddenFor(model => model.Created)
        <div class="form-group">
            @Html.LabelFor(model => model.Created, "Created", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mediaURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="image" type="file" class="form-control" id="fileUpload" />
                @Html.ValidationMessageFor(model => model.mediaURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.published)
                    @Html.ValidationMessageFor(model => model.published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            tinymce.init({
                selector: '#Body'
            });
        });
    </script>
}

Views/BlogPosts/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<D2Blog.Models.BlogPost>

<body>
    @if (User.IsInRole("Admin"))
    {
        <div class="col-md-8 blog-main">
            <div class="row">
                @foreach (var item in Model)
                {

                    <div class="col-md-6 col-sm-6">
                        <article class="blog-teaser index">
                            <header>
                                <img src="@item.mediaURL" width="184" height="184" />
                                <h3>@item.Title</h3>
                                <span class="meta">@item.Created.ToString("dd MMM yyyy") , Wilten Houston</span>
                                <hr>
                            </header>
                            <div class="body">
                                @Html.Raw(item.Body)
                            </div>
                            <div class="clearfix">

                                @Html.ActionLink("Read More", "Details", new { Slug = item.Slug }, new { @class = "btn btn-tales-one" })
                                @if ((User.Identity.IsAuthenticated) && (User.IsInRole("Admin")))
                                {
                                    @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "btn btn-tales-one" })

                                    @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btn btn-tales-one" })
                                }

                            </div>
                        </article>
                    </div>
                }
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

            </div>
        </div>
    }
    else
    {
        <div class="col-md-8 blog-main">
            <div class="row">
                @foreach (var item in Model.Where(p => p.published == true))
                {

                    <div class="col-md-6 col-sm-6">
                        <article class="blog-teaser index">
                            <span class="index">
                                <header>
                                    <img src="@item.mediaURL" width="184" height="184" />
                                    <h3>@item.Title</h3>
                                    <span class="meta">@item.Created.ToString("dd MMM yyyy") , Wilten Houston</span>
                                    <hr>
                                </header>
                                <div class="body">
                                    @Html.Raw(item.Body)
                                </div>
                                <div class="clearfix">

                                    @Html.ActionLink("Read More", "Details", new { Slug = item.Slug }, new { @class = "btn btn-tales-one" })
                                    @if ((User.Identity.IsAuthenticated) && (User.IsInRole("Admin")))
                                    {
                                        @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "btn btn-tales-one" })

                                        @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btn btn-tales-one" })
                                    }

                                </div>
                            </span>
                        </article>
                    </div>
                }
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

            </div>
        </div>
        <aside class="col-md-4 blog-aside">

            <div class="aside-widget">
                <header>
                    <h3 class="index">New Blogs In Progress...</h3>
                </header>
                <div class="body index">
                    <ul class="tales-list">
                        @foreach (var item in Model.Where(p => p.published == false))
                        {
                            <li>@item.Title</li>
                        }

                    </ul>
                </div>
            </div>
        </aside>
    }
</body>